name: tobetoapp
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.5
  flutter_bloc: ^8.1.5
  cloud_firestore: ^4.17.3
  google_sign_in: ^6.2.1
  uuid: ^4.4.0
  intl: ^0.19.0
  password_strength_checker: ^1.2.3
  toggle_switch: ^2.3.0
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2
  url_launcher: ^6.2.6
  video_player: ^2.8.6
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  
  assets:
    - assets/logo/tobetologo.PNG
    - assets/logo/advancity.jpg
    - assets/logo/code2.png
    - assets/logo/enocta.png
    - assets/logo/perculus.jpg
    - assets/logo/talent.png
    - assets/logo/tobeto.png
    - assets/pictures/foto1.jpg
    - assets/pictures/foto2.jpg
    - assets/pictures/foto3.webp
    - assets/pictures/foto4.jpg
    - assets/pictures/foto5.png
    - assets/pictures/foto6.jpg
    - assets/pictures/foto7.jpg
    - assets/pictures/1ai.png
    - assets/pictures/2proje.png
    - assets/pictures/3fullstack.png
    - assets/pictures/4analiz.png
    - assets/pictures/5digital.png
    - assets/pictures/6test.png
    - assets/gif/spider_light.gif
    - assets/video/tobeto_video.mp4
    - assets/ekip/ali_seyhan.jpg
    - assets/ekip/elif_kilic.jpeg
    - assets/ekip/gurkan_ilisen.jfif
    - assets/ekip/kader_yavuz.jpg
    - assets/ekip/pelin_batir.png

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

